// "/" commands built into Claude Code, Codex and omp, captured from
// their terminal menu (Claude Code from September 2026, Codex 0.157, omp 18.4).
// Personal skills and commands (~/.claude/skills, ~/.claude/commands,
// project folder, ~/.codex/prompts, ~/.omp/agent/commands…) are read on the
// machine, see slash.ts.
// [name, description, arguments?]
export type SlashEntry = [string, string, string?]

export const CLAUDE_BUILTIN: SlashEntry[] = [
  ["claude-in-chrome", "Automates your Chrome browser to interact with web pages - clicking elements, filling forms, capturing screenshots, reading console log"],
  ["run", "Launch and drive this project's app to see a change working. Use when asked to run, start, or screenshot the app, or to confirm a ch"],
  ["add-dir", "Add a new working directory"],
  ["advisor", "Let Claude consult a stronger model at key moments"],
  ["artifacts", "Browse your published and shared artifacts"],
  ["auto-mode-setup", "Teach auto mode about your environment, plus optional rule tweaks"],
  ["autocompact", "Set how full the context gets before auto-summarizing"],
  ["autofix-pr", "Monitor and autofix any issues with the current PR"],
  ["background", "Send this session to the background and free the terminal"],
  ["branch", "Create a branch of the current conversation at this point"],
  ["btw", "Ask a quick side question without interrupting the main conversation"],
  ["bug", "Report a bug or share your conversation"],
  ["cd", "Move this session to a new working directory"],
  ["chrome", "Open Claude in Chrome settings"],
  ["clear", "Start a new session with empty context; previous session stays on disk (resumable with /resume)"],
  ["color", "Set the prompt bar color for this session"],
  ["compact", "Free up context by summarizing the conversation so far"],
  ["config", "Open settings"],
  ["context", "Visualize current context usage as a colored grid"],
  ["copy", "Copy Claude's last response to clipboard (or /copy N for the Nth-latest)"],
  ["design-login", "Authorize design-system access for /design-sync with your claude.ai account"],
  ["diff", "Toggle the diff panel showing uncommitted changes"],
  ["effort", "Set effort level for model usage"],
  ["exit", "Exit the CLI"],
  ["export", "Export the current conversation to a file or clipboard"],
  ["fast", "Toggle fast mode (Opus 5.5)"],
  ["feedback", "Send feedback to Anthropic or report a bug"],
  ["focus", "Toggle focus view: just your prompt, summary, and response"],
  ["fork", "Copy this conversation into a new background session and keep working here"],
  ["goal", "Set a goal Claude checks before stopping"],
  ["help", "Show help and available commands"],
  ["hooks", "View hook configurations for tool events"],
  ["ide", "Manage IDE integrations and show status"],
  ["import", "Import config from another AI coding agent"],
  ["install-github-app", "Set up Claude GitHub Actions for a repository"],
  ["install-slack-app", "Install the Claude Slack app"],
  ["keybindings", "Open your keyboard shortcuts file"],
  ["list-agents", "List subagents, teammates, and other Claude sessions you can message"],
  ["login", "Sign in with your Anthropic account"],
  ["logout", "Sign out from your Anthropic account"],
  ["mcp", "Manage MCP servers"],
  ["memory", "Edit CLAUDE.md files and memory settings"],
  ["mobile", "Show QR code to download the Claude mobile app"],
  ["model", "Set the AI model for Claude Code (currently Sonnet 5)"],
  ["output-style", "List output styles or switch to one"],
  ["passes", "Share a free week of Claude Code with friends and earn usage credits"],
  ["permissions", "Manage allow and deny tool permission rules"],
  ["plan", "Enable plan mode or view the current session plan"],
  ["plugin", "Manage Claude Code plugins"],
  ["powerup", "Discover Claude Code features through quick interactive lessons"],
  ["privacy-settings", "View and update your privacy settings"],
  ["radio", "Listen to Claude FM lo-fi radio"],
  ["recap", "Generate a one-line session recap now"],
  ["release-notes", "View release notes"],
  ["reload-plugins", "Activate pending plugin changes in the current session"],
  ["reload-skills", "Pick up skills added or changed on disk during this session"],
  ["remote-control", "Control this session from your phone or claude.ai/code"],
  ["remote-env", "Choose the default environment for cloud agents"],
  ["rename", "Rename the current conversation"],
  ["resume", "Resume a previous conversation"],
  ["rewind", "Restore the code and/or conversation to a previous point"],
  ["sandbox", "◯ sandbox disabled (⏎ to configure)"],
  ["scroll-speed", "Adjust mouse wheel scroll speed"],
  ["skill-doctor", "Show which loaded skills are unused and costing context"],
  ["skills", "List available skills"],
  ["status", "Show Claude Code status including version, model, account, API connectivity, and tool statuses"],
  ["stickers", "Order Claude Code stickers"],
  ["subtask", "Send a subagent off with your full context; its result comes back here"],
  ["tasks", "View and manage everything running in the background"],
  ["teleport", "Send this session to the cloud, or resume one from claude.ai"],
  ["terminal-setup", "Install Shift+Enter key binding for newlines"],
  ["theme", "Change the theme"],
  ["tui", "Set the terminal UI renderer (default | fullscreen)"],
  ["ultrareview", "3 free left · Start a cloud agent that finds and verifies bugs in your branch (~15-25 min, $5-$25 USD) · Runs in a cloud session. See"],
  ["upgrade", "Upgrade to Max for higher rate limits and more Opus"],
  ["usage", "Show session cost, plan usage, and activity stats"],
  ["usage-credits", "Configure usage credits or request them from your admin when you hit a limit"],
  ["voice", "Toggle voice mode"],
  ["web-setup", "Set up cloud sessions with your GitHub account"],
  ["workflows", "Browse running and completed workflows"],
  ["artifact-capabilities", "Runtime capabilities a published Artifact page can be granted — behavior static HTML cannot provide on its own, such as the page re"],
  ["artifact-diagramming", "Diagramming know-how for Artifacts - when a picture earns its place, how to draw one that shows the real mechanism, and the inline-SVG m"],
  ["batch", "Research and plan a large-scale change, then execute it in parallel across 5–30 isolated worktree agents that each open a PR."],
  ["claude-api", "Reference for the Claude API / Anthropic SDK — model ids, pricing, params, streaming, tool use, MCP, agents, caching, token counting,"],
  ["code-review", "Review the current diff, or a PR number/branch/path target, for correctness bugs (plus reuse/simplif"],
  ["dataviz", "Use this skill whenever you are about to create ANY chart, graph, plot, dashboard, or data visualization, in ANY output medium — an H"],
  ["debug", "Enable debug logging for this session and help diagnose issues"],
  ["deep-research", "Deep research harness — fan-out web searches, fetch sources, adversarially verify claims, synt"],
  ["design", "Make a new Design artifact from a brief"],
  ["design-sync", "Push a React design system to claude.ai/design. This runs a converter that bundles the real component code (from Storybook or a"],
  ["doctor", "Health-check the user's Claude Code setup and fix issues: diagnose installation health — what the `claude doctor` terminal diagnostics"],
  ["fewer-permission-prompts", "Scan your transcripts for common read-only Bash and MCP tool calls, then add a prioritized allowlist to project .claude/settings.json t"],
  ["init", "Initialize a new CLAUDE.md file with codebase documentation"],
  ["insights", "Generate a report analyzing your Claude Code sessions"],
  ["loop", "Run a prompt or slash command on a recurring interval (e.g. /loop 5m /foo). Omit the interval to let the model self-pace."],
  ["run-skill-generator", "Author or improve the run-<unit> skill - a per-project skill that tells agents how to build, launch, and drive this project's app. Us"],
  ["schedule", "Create, update, list, or run scheduled cloud agents (routines) that execute on a cron schedule."],
  ["security-review", "Complete a security review of the pending changes on the current branch"],
  ["simplify", "Review the changed code for reuse, simplification, efficiency, and altitude cleanups, then apply the fixes. Quality only — it does not"],
  ["slides", "Make a new Slides deck artifact from a brief"],
  ["statusline", "Set up Claude Code's status line UI"],
  ["team-onboarding", "Help teammates ramp on Claude Code with a guide from your usage"],
  ["update-config", "Use this skill to configure the Claude Code harness via settings.json. Automated behaviors (\"from now on when X\", \"each tim"],
  ["verify", "Verify that a code change actually does what it's supposed to by exercising it end-to-end and observing behavior — drive the affecte"],
  ["workflow-authoring", "Reference for writing a Workflow tool script (script API and gotchas, resume, quality patterns, worked examples). Load before au"],
]

export const CODEX_BUILTIN: SlashEntry[] = [
  ["model", "choose what model and reasoning effort to use"],
  ["fast", "1.5x speed"],
  ["ide", "include current selection, open files, and other context from your IDE"],
  ["permissions", "choose what Codex is allowed to do"],
  ["keymap", "remap TUI shortcuts"],
  ["vim", "toggle Vim mode for the composer"],
  ["experimental", "toggle experimental features"],
  ["approve", "approve one retry of a recent auto-review denial"],
  ["memories", "configure memory use and generation"],
  ["skills", "use skills to improve how Codex performs specific tasks"],
  ["import", "import setup, this project, and recent chats from Claude Code"],
  ["hooks", "view and manage lifecycle hooks"],
  ["review", "review my current changes and find issues"],
  ["rename", "rename the current thread"],
  ["new", "start a new chat during a conversation"],
  ["archive", "archive this session"],
  ["delete", "permanently delete this session"],
  ["resume", "resume a saved chat"],
  ["fork", "fork the current chat"],
  ["worktree", "start or continue a conversation in a new worktree"],
  ["init", "create an AGENTS.md file with instructions for Codex"],
  ["compact", "summarize conversation to prevent hitting the context limit"],
  ["recap", "summarize the current conversation now"],
  ["plan", "switch to Plan mode"],
  ["voice", "start or stop voice; use /voice settings to choose a voice"],
  ["goal", "set or view the goal for a long-running task"],
  ["agents", "open the agent command center"],
  ["side", "start a side conversation in an ephemeral fork"],
  ["copy", "copy the last response or part of it"],
  ["export", "export the conversation as markdown"],
  ["raw", "toggle raw scrollback mode for copy-friendly terminal selection"],
  ["tui", "choose the TUI mode for the next launch"],
  ["diff", "show git diff (including untracked files)"],
  ["mention", "mention a file"],
  ["status", "show current session configuration and token usage"],
  ["daemon", "Manage the local background server"],
  ["warnings", "view retained warnings and diagnostic details"],
  ["cd", "change the current working directory"],
  ["pwd", "show the current working directory"],
  ["usage", "view account usage or use a usage limit reset"],
  ["title", "configure which items appear in the terminal title"],
  ["statusline", "configure which items appear in the status line"],
  ["theme", "choose a syntax highlighting theme"],
  ["pets", "choose or hide the terminal pet"],
  ["mcp", "list configured MCP tools; use /mcp verbose for details"],
  ["plugins", "browse plugins"],
  ["logout", "log out of Codex"],
  ["exit", "exit Codex"],
  ["feedback", "send logs to maintainers"],
  ["ps", "list background terminals"],
  ["stop", "stop all background terminals"],
  ["clear", "clear the terminal and start a new chat"],
  ["subagents", "switch between this session's subagents"],
]

// omp 18.4 (BUILTIN_SLASH_COMMAND_DEFS of pi-coding-agent), without aliases.
export const OMP_BUILTIN: SlashEntry[] = [
  ["security", "Plan, run, inspect, import, and compare OMP-native security scans"],
  ["settings", "Open settings menu"],
  ["setup", "Open provider setup"],
  ["plan", "Toggle plan mode (agent plans before executing)", "[prompt]"],
  ["plan-review", "Re-open the plan review for the latest plan (plan mode only)"],
  ["vibe", "Toggle vibe mode (direct persistent fast/good worker sessions; read-only toolset)", "[prompt]"],
  ["goal", "Toggle goal mode (persistent autonomous objective for this session)", "[objective]"],
  ["guided-goal", "Have the agent interview you in chat, then set up goal mode", "[rough objective]"],
  ["loop", "Toggle loop mode. While enabled, the next prompt you send re-submits after every yield. Esc cancels the current iteration; /loop again to disable.", "[count|duration] [prompt]"],
  ["queue", "Queue a message for after the agent yields", "<message>"],
  ["model", "Switch model for this session"],
  ["switch", "Switch model for this session (same as alt+p)"],
  ["fast", "Toggle priority service tier (OpenAI service_tier=priority, Anthropic speed=fast)"],
  ["computer", "Toggle the native computer-use tool for this session"],
  ["vision", "Control the inspect_image vision-delegation tool for this session"],
  ["prewalk", "Switch to a fast/cheap model at the next action (works even without --prewalk)"],
  ["advisor", "Toggle the advisor (a second model that reviews each turn and injects notes)"],
  ["export", "Export session to HTML file", "[--themes] [path]"],
  ["dump", "Copy session transcript to clipboard (and write LLM request JSON to tmp)"],
  ["share", "Share session via an encrypted link (share server or secret gist)"],
  ["collab", "Share this session live via a relay", "[start|view|stop|status] [relayUrl]"],
  ["join", "Join a shared collab session", "<link>"],
  ["leave", "Leave the collab session"],
  ["browser", "Toggle browser headless vs visible mode"],
  ["copy", "Pick text or code from the conversation to copy"],
  ["todo", "View or modify the agent's todo list"],
  ["session", "Session management commands"],
  ["jobs", "Show async background jobs status"],
  ["usage", "Show provider usage and limits"],
  ["stats", "Launch the local stats dashboard", "[--port <port>] [--host <host>]"],
  ["changelog", "Show changelog entries"],
  ["hotkeys", "Show all keyboard shortcuts"],
  ["tools", "Show tools currently visible to the agent"],
  ["context", "Show estimated context usage breakdown"],
  ["extensions", "Open Extension Control Center dashboard"],
  ["agents", "Open the agents hub (per-agent model, prewalk, and advisor)"],
  ["branch", "Create a new branch from a previous message"],
  ["fork", "Create a new fork from a previous message"],
  ["tree", "Navigate session tree (switch branches)"],
  ["login", "Login with OAuth provider", "[provider|redirect URL]"],
  ["logout", "Logout from OAuth provider", "[provider]"],
  ["mcp", "Manage MCP servers (add, list, remove, test)", "<subcommand>"],
  ["ssh", "Manage SSH hosts (add, list, remove)", "<subcommand>"],
  ["new", "Start a new session"],
  ["fresh", "Reset provider stream state without changing the local transcript"],
  ["clear", "Clear the conversation context in place, keeping the session"],
  ["drop", "Delete the current session and start a new one"],
  ["compact", "Manually compact the session context"],
  ["shake", "Drop heavy content from context (tool results, large blocks)"],
  ["handoff", "Hand off session context to a new session", "[focus instructions]"],
  ["resume", "Resume a different session", "[session id|@claude|@codex]"],
  ["btw", "Ask an ephemeral side question using the current session context", "<question>"],
  ["tan", "Run a full background agent on tangential work", "<work>"],
  ["omfg", "Forge a TTSR rule from a complaint to stop a recurring behavior", "<complaint>"],
  ["retry", "Retry the last failed agent turn"],
  ["debug", "Open debug tools selector"],
  ["memory", "Inspect and operate memory maintenance"],
  ["rename", "Rename the current session", "<title>"],
  ["move", "Move the current session to a different directory", "[<path>]"],
  ["add-dir", "Add a workspace directory to this session (multi-root)", "<path>"],
  ["remove-dir", "Remove a workspace directory from this session", "<path>"],
  ["dirs", "List this session's workspace directories"],
  ["exit", "Exit the application"],
  ["marketplace", "Manage marketplace plugin sources and installed plugins"],
  ["plugins", "View and manage installed plugins"],
  ["reload-plugins", "Reload all plugins (skills, commands, hooks, tools, agents, MCP)"],
  ["force", "Force next turn to use a specific tool", "<tool-name> [prompt]"],
  ["live", "Start Codex-backed realtime voice mode"],
  ["pause", "Freeze all agents (main, subagents, advisor) until resumed"],
  ["quit", "Quit the application"],
]
